[build]
command = "npm run build"
publish = "dist"

[[plugins]]
package = "@netlify/plugin-lighthouse"

[plugins.inputs.settings]
preset = "desktop"

[[headers]]
for = "/*"
[headers.values]
cache-control = "no-cache, no-store, must-revalidate"
